INSERT INTO ratemycourse.Courses (courseNumber, courseName) VALUES ('CSCI 410x', 'Translation of Programming Languages');
INSERT INTO ratemycourse.Courses (courseNumber, courseName) VALUES ('CSCI 490x', 'Directed Research');
INSERT INTO ratemycourse.Courses (courseNumber, courseName) VALUES ('CSCI 646', 'Coordinated Mobile Robotics');
INSERT INTO ratemycourse.Courses (courseNumber, courseName) VALUES ('CSCI 648', 'Advanced Information Integration');
INSERT INTO ratemycourse.Courses (courseNumber, courseName) VALUES ('CSCI 657', 'Advanced Distributed Systems');
INSERT INTO ratemycourse.Courses (courseNumber, courseName) VALUES ('CSCI 670x', 'Advanced Analysis of Algorithms');
INSERT INTO ratemycourse.Courses (courseNumber, courseName) VALUES ('CSCI 698', 'Practicum in Teaching Computer Science');
INSERT INTO ratemycourse.Courses (courseNumber, courseName) VALUES ('CSCI 697', 'Seminar in Computer Science Research');
INSERT INTO ratemycourse.Courses (courseNumber, courseName) VALUES ('CSCI 491aL', 'Final Game Project');
INSERT INTO ratemycourse.Courses (courseNumber, courseName) VALUES ('CSCI 101L', 'Fundamentals of Computer Programming');
INSERT INTO ratemycourse.Courses (courseNumber, courseName) VALUES ('CSCI 103L', 'Introduction to Programming');
INSERT INTO ratemycourse.Courses (courseNumber, courseName) VALUES ('CSCI 104L', 'Data Structures and Object Oriented Design');
INSERT INTO ratemycourse.Courses (courseNumber, courseName) VALUES ('CSCI 109', 'Introduction to Computer Science');
INSERT INTO ratemycourse.Courses (courseNumber, courseName) VALUES ('CSCI 170', 'Discrete Methods in Computer Science');
INSERT INTO ratemycourse.Courses (courseNumber, courseName) VALUES ('CSCI 201L', 'Principles of Software Development');
INSERT INTO ratemycourse.Courses (courseNumber, courseName) VALUES ('CSCI 270', 'Introduction to Algorithms and Theory of Computing');
INSERT INTO ratemycourse.Courses (courseNumber, courseName) VALUES ('CSCI 281', 'Pipelines for Games and Interactives');
INSERT INTO ratemycourse.Courses (courseNumber, courseName) VALUES ('CSCI 310', 'Software Engineering');
INSERT INTO ratemycourse.Courses (courseNumber, courseName) VALUES ('CSCI 350', 'Introduction to Operating Systems');
INSERT INTO ratemycourse.Courses (courseNumber, courseName) VALUES ('CSCI 352L', 'Computer Organization and Architecture');
INSERT INTO ratemycourse.Courses (courseNumber, courseName) VALUES ('CSCI 353', 'Introduction to Internetworking');
INSERT INTO ratemycourse.Courses (courseNumber, courseName) VALUES ('CSCI 360', 'Introduction to Artificial Intelligence');
INSERT INTO ratemycourse.Courses (courseNumber, courseName) VALUES ('CSCI 380', 'Video Game Programming');
INSERT INTO ratemycourse.Courses (courseNumber, courseName) VALUES ('CSCI 390', 'Special Problems');
INSERT INTO ratemycourse.Courses (courseNumber, courseName) VALUES ('CSCI 402', 'Operating Systems');
INSERT INTO ratemycourse.Courses (courseNumber, courseName) VALUES ('CSCI 420', 'Computer Graphics');
INSERT INTO ratemycourse.Courses (courseNumber, courseName) VALUES ('CSCI 423', 'Native Console Multiplayer Game Development');
INSERT INTO ratemycourse.Courses (courseNumber, courseName) VALUES ('CSCI 430', 'Introduction to Computer and Network Security');
INSERT INTO ratemycourse.Courses (courseNumber, courseName) VALUES ('CSCI 445L', 'Introduction to Robotics');
INSERT INTO ratemycourse.Courses (courseNumber, courseName) VALUES ('CSCI 450', 'Introduction to Computer Networks');
INSERT INTO ratemycourse.Courses (courseNumber, courseName) VALUES ('CSCI 452', 'Parallel and Distributed Computation');
INSERT INTO ratemycourse.Courses (courseNumber, courseName) VALUES ('CSCI 454L', 'Introduction to System-on-Chip');
INSERT INTO ratemycourse.Courses (courseNumber, courseName) VALUES ('CSCI 455x', 'Introduction to Programming Systems Design');
INSERT INTO ratemycourse.Courses (courseNumber, courseName) VALUES ('CSCI 457', 'Computer Systems Organization');
INSERT INTO ratemycourse.Courses (courseNumber, courseName) VALUES ('CSCI 458', 'Numerical Methods');
INSERT INTO ratemycourse.Courses (courseNumber, courseName) VALUES ('CSCI 459', 'Computer Systems and Applications Modeling Fundamentals');
INSERT INTO ratemycourse.Courses (courseNumber, courseName) VALUES ('CSCI 476', 'Cryptography: Secure Communication and Computation');
INSERT INTO ratemycourse.Courses (courseNumber, courseName) VALUES ('CSCI 485', 'File and Database Management');
INSERT INTO ratemycourse.Courses (courseNumber, courseName) VALUES ('CSCI 487', 'Programming Game Engines');
INSERT INTO ratemycourse.Courses (courseNumber, courseName) VALUES ('CSCI 491bL', 'Final Game Project');
INSERT INTO ratemycourse.Courses (courseNumber, courseName) VALUES ('CSCI 495', 'Senior Project');
INSERT INTO ratemycourse.Courses (courseNumber, courseName) VALUES ('CSCI 499', 'Special Topics');
INSERT INTO ratemycourse.Courses (courseNumber, courseName) VALUES ('CSCI 501', 'Numerical Analysis and Computation');
INSERT INTO ratemycourse.Courses (courseNumber, courseName) VALUES ('CSCI 502a', 'Numerical Analysis');
INSERT INTO ratemycourse.Courses (courseNumber, courseName) VALUES ('CSCI 502b', 'Numerical Analysis');
INSERT INTO ratemycourse.Courses (courseNumber, courseName) VALUES ('CSCI 504a', 'Numerical Solutions of Ordinary and Partial Differential Equations');
INSERT INTO ratemycourse.Courses (courseNumber, courseName) VALUES ('CSCI 504b', 'Numerical Solutions of Ordinary and Partial Differential Equations');
INSERT INTO ratemycourse.Courses (courseNumber, courseName) VALUES ('CSCI 505a', 'Applied Probability');
INSERT INTO ratemycourse.Courses (courseNumber, courseName) VALUES ('CSCI 505b', 'Applied Probability');
INSERT INTO ratemycourse.Courses (courseNumber, courseName) VALUES ('CSCI 510', 'Software Management and Economics');
INSERT INTO ratemycourse.Courses (courseNumber, courseName) VALUES ('CSCI 511', 'Personal Software Process (PSP) and Project');
INSERT INTO ratemycourse.Courses (courseNumber, courseName) VALUES ('CSCI 512', 'Testing and Analysis of Software Systems');
INSERT INTO ratemycourse.Courses (courseNumber, courseName) VALUES ('CSCI 520', 'Computer Animation and Simulation');
INSERT INTO ratemycourse.Courses (courseNumber, courseName) VALUES ('CSCI 521', 'Optimization: Theory and Algorithms');
INSERT INTO ratemycourse.Courses (courseNumber, courseName) VALUES ('CSCI 522', 'Game Engine Development');
INSERT INTO ratemycourse.Courses (courseNumber, courseName) VALUES ('CSCI 523L', 'Networked Games');
INSERT INTO ratemycourse.Courses (courseNumber, courseName) VALUES ('CSCI 524', 'Networked Artificial Intelligence');
INSERT INTO ratemycourse.Courses (courseNumber, courseName) VALUES ('CSCI 526', 'Advanced Mobile Devices and Game Consoles');
INSERT INTO ratemycourse.Courses (courseNumber, courseName) VALUES ('CSCI 529a', 'Advanced Game Projects');
INSERT INTO ratemycourse.Courses (courseNumber, courseName) VALUES ('CSCI 529b', 'Advanced Game Projects');
INSERT INTO ratemycourse.Courses (courseNumber, courseName) VALUES ('CSCI 530', 'Security Systems');
INSERT INTO ratemycourse.Courses (courseNumber, courseName) VALUES ('CSCI 531', 'Applied Cryptography');
INSERT INTO ratemycourse.Courses (courseNumber, courseName) VALUES ('CSCI 533', 'Algebraic Combinatorics');
INSERT INTO ratemycourse.Courses (courseNumber, courseName) VALUES ('CSCI 534', 'Affective Computing');
INSERT INTO ratemycourse.Courses (courseNumber, courseName) VALUES ('CSCI 536', 'Linear Programming and Extensions');
INSERT INTO ratemycourse.Courses (courseNumber, courseName) VALUES ('CSCI 540', 'Self-Organization');
INSERT INTO ratemycourse.Courses (courseNumber, courseName) VALUES ('CSCI 542', 'Neural Computation with Artificial Neural Networks');
INSERT INTO ratemycourse.Courses (courseNumber, courseName) VALUES ('CSCI 544', 'Applied Natural Language Processing');
INSERT INTO ratemycourse.Courses (courseNumber, courseName) VALUES ('CSCI 545', 'Robotics');
INSERT INTO ratemycourse.Courses (courseNumber, courseName) VALUES ('CSCI 548', 'Information Integration on the Web');
INSERT INTO ratemycourse.Courses (courseNumber, courseName) VALUES ('CSCI 549', 'Nanorobotics');
INSERT INTO ratemycourse.Courses (courseNumber, courseName) VALUES ('CSCI 550', 'Advanced Data Stores');
INSERT INTO ratemycourse.Courses (courseNumber, courseName) VALUES ('CSCI 551', 'Computer Networking');
INSERT INTO ratemycourse.Courses (courseNumber, courseName) VALUES ('CSCI 553', 'Computational Solution of Optimization Problems');
INSERT INTO ratemycourse.Courses (courseNumber, courseName) VALUES ('CSCI 554', 'Cyber-Physical Systems: A Computing Perspective');
INSERT INTO ratemycourse.Courses (courseNumber, courseName) VALUES ('CSCI 555L', 'Advanced Operating Systems');
INSERT INTO ratemycourse.Courses (courseNumber, courseName) VALUES ('CSCI 556', 'Introduction to Cryptography');
INSERT INTO ratemycourse.Courses (courseNumber, courseName) VALUES ('CSCI 557', 'Computer Systems Architecture');
INSERT INTO ratemycourse.Courses (courseNumber, courseName) VALUES ('CSCI 558L', 'Internetworking and Distributed Systems Laboratory');
INSERT INTO ratemycourse.Courses (courseNumber, courseName) VALUES ('CSCI 559', 'Machine Learning I: Supervised Methods');
INSERT INTO ratemycourse.Courses (courseNumber, courseName) VALUES ('CSCI 561', 'Foundations of Artificial Intelligence');
INSERT INTO ratemycourse.Courses (courseNumber, courseName) VALUES ('CSCI 564', 'Brain Theory and Artificial Intelligence');
INSERT INTO ratemycourse.Courses (courseNumber, courseName) VALUES ('CSCI 565', 'Compiler Design');
INSERT INTO ratemycourse.Courses (courseNumber, courseName) VALUES ('CSCI 567', 'Machine Learning');
INSERT INTO ratemycourse.Courses (courseNumber, courseName) VALUES ('CSCI 568', 'Requirements Engineering');
INSERT INTO ratemycourse.Courses (courseNumber, courseName) VALUES ('CSCI 570', 'Analysis of Algorithms');
INSERT INTO ratemycourse.Courses (courseNumber, courseName) VALUES ('CSCI 571', 'Web Technologies');
INSERT INTO ratemycourse.Courses (courseNumber, courseName) VALUES ('CSCI 572', 'Information Retrieval and Web Search Engines');
INSERT INTO ratemycourse.Courses (courseNumber, courseName) VALUES ('CSCI 573', 'Probabilistic Reasoning');
INSERT INTO ratemycourse.Courses (courseNumber, courseName) VALUES ('CSCI 574', 'Computer Vision');
INSERT INTO ratemycourse.Courses (courseNumber, courseName) VALUES ('CSCI 575', 'Quantum Computing and Quantum Cryptography');
INSERT INTO ratemycourse.Courses (courseNumber, courseName) VALUES ('CSCI 576', 'Multimedia Systems Design');
INSERT INTO ratemycourse.Courses (courseNumber, courseName) VALUES ('CSCI 577a', 'Software Engineering');
INSERT INTO ratemycourse.Courses (courseNumber, courseName) VALUES ('CSCI 577b', 'Software Engineering');
INSERT INTO ratemycourse.Courses (courseNumber, courseName) VALUES ('CSCI 578', 'Software Architectures');
INSERT INTO ratemycourse.Courses (courseNumber, courseName) VALUES ('CSCI 580', '3-D Graphics and Rendering');
INSERT INTO ratemycourse.Courses (courseNumber, courseName) VALUES ('CSCI 581', 'Logic and its Applications');
INSERT INTO ratemycourse.Courses (courseNumber, courseName) VALUES ('CSCI 582', 'Geometric Modeling');
INSERT INTO ratemycourse.Courses (courseNumber, courseName) VALUES ('CSCI 585', 'Database Systems');
INSERT INTO ratemycourse.Courses (courseNumber, courseName) VALUES ('CSCI 586', 'Database Systems Interoperability');
INSERT INTO ratemycourse.Courses (courseNumber, courseName) VALUES ('CSCI 587', 'Geospatial Information Management');
INSERT INTO ratemycourse.Courses (courseNumber, courseName) VALUES ('CSCI 589', 'Software Engineering for Embedded Systems');
INSERT INTO ratemycourse.Courses (courseNumber, courseName) VALUES ('CSCI 590', 'Directed Research');
INSERT INTO ratemycourse.Courses (courseNumber, courseName) VALUES ('CSCI 594a', 'Master’s Thesis');
INSERT INTO ratemycourse.Courses (courseNumber, courseName) VALUES ('CSCI 594b', 'Master’s Thesis');
INSERT INTO ratemycourse.Courses (courseNumber, courseName) VALUES ('CSCI 594z', 'Master’s Thesis');
INSERT INTO ratemycourse.Courses (courseNumber, courseName) VALUES ('CSCI 596', 'Scientific Computing and Visualization');
INSERT INTO ratemycourse.Courses (courseNumber, courseName) VALUES ('CSCI 599', 'Special Topics');
INSERT INTO ratemycourse.Courses (courseNumber, courseName) VALUES ('CSCI 621', 'Digital Geometry Processing');
INSERT INTO ratemycourse.Courses (courseNumber, courseName) VALUES ('CSCI 652', 'Internet Measurement');
INSERT INTO ratemycourse.Courses (courseNumber, courseName) VALUES ('CSCI 653', 'High Performance Computing and Simulations');
INSERT INTO ratemycourse.Courses (courseNumber, courseName) VALUES ('CSCI 658', 'Diagnosis and Design of Reliable Digital Systems');
INSERT INTO ratemycourse.Courses (courseNumber, courseName) VALUES ('CSCI 662', 'Advanced Natural Language Processing');
INSERT INTO ratemycourse.Courses (courseNumber, courseName) VALUES ('CSCI 671', 'Randomized Algorithms');
INSERT INTO ratemycourse.Courses (courseNumber, courseName) VALUES ('CSCI 672', 'Approximation Algorithms');
INSERT INTO ratemycourse.Courses (courseNumber, courseName) VALUES ('CSCI 673', 'Structure and Dynamics of Networked Information');
INSERT INTO ratemycourse.Courses (courseNumber, courseName) VALUES ('CSCI 674a', 'Advanced Topics in Computer Vision');
INSERT INTO ratemycourse.Courses (courseNumber, courseName) VALUES ('CSCI 675', 'Convex and Combinatorial Optimization');
INSERT INTO ratemycourse.Courses (courseNumber, courseName) VALUES ('CSCI 685', 'Advanced Topics in Database Systems');
INSERT INTO ratemycourse.Courses (courseNumber, courseName) VALUES ('CSCI 686', 'Advanced Big Data Analytics');
INSERT INTO ratemycourse.Courses (courseNumber, courseName) VALUES ('CSCI 674b', 'Advanced Topics in Computer Vision');
INSERT INTO ratemycourse.Courses (courseNumber, courseName) VALUES ('CSCI 790', 'Research');
INSERT INTO ratemycourse.Courses (courseNumber, courseName) VALUES ('CSCI 794a', 'Doctoral Dissertation');
INSERT INTO ratemycourse.Courses (courseNumber, courseName) VALUES ('CSCI 794b', 'Doctoral Dissertation');
INSERT INTO ratemycourse.Courses (courseNumber, courseName) VALUES ('CSCI 794c', 'Doctoral Dissertation');
INSERT INTO ratemycourse.Courses (courseNumber, courseName) VALUES ('CSCI 794d', 'Doctoral Dissertation');
INSERT INTO ratemycourse.Courses (courseNumber, courseName) VALUES ('CSCI 794z', 'Doctoral Dissertation');
INSERT INTO ratemycourse.Courses (courseNumber, courseName) VALUES ('CSCI 404', 'Capstone: Creating Your High-Tech Startup');
INSERT INTO ratemycourse.Courses (courseNumber, courseName) VALUES ('CSCI 591', 'Computer Science Research Colloquium');
INSERT INTO ratemycourse.Courses (courseNumber, courseName) VALUES ('CSCI 620', 'Computer Animation and Simulation');
INSERT INTO ratemycourse.Courses (courseNumber, courseName) VALUES ('CSCI 401', 'Capstone: Design and Construction of Large Software Systems');
INSERT INTO ratemycourse.Courses (courseNumber, courseName) VALUES ('CSCI 535', 'Multimodal Probabilistic Learning of Human Communication');
INSERT INTO ratemycourse.Courses (courseNumber, courseName) VALUES ('CSCI 651', 'Advanced Computer Networking');
INSERT INTO ratemycourse.Courses (courseNumber, courseName) VALUES ('CSCI 668', 'Search and Planning');
INSERT INTO ratemycourse.Courses (courseNumber, courseName) VALUES ('CSCI 598', 'Professional Writing and Communication for Computer Scientists');
INSERT INTO ratemycourse.Courses (courseNumber, courseName) VALUES ('CSCI 593', 'Mathematical Foundations for System Design: Modeling, Analysis, and Synthesis');
INSERT INTO ratemycourse.Courses (courseNumber, courseName) VALUES ('CSCI 368', 'Programming Graphical User Interfaces');
INSERT INTO ratemycourse.Courses (courseNumber, courseName) VALUES ('CSCI 435', 'Professional C++');
INSERT INTO ratemycourse.Courses (courseNumber, courseName) VALUES ('CSCI 439', 'Compiler Development');
INSERT INTO ratemycourse.Courses (courseNumber, courseName) VALUES ('CSCI 100xg', 'Explorations in Computing');
INSERT INTO ratemycourse.Courses (courseNumber, courseName) VALUES ('CSCI 610', 'Advanced Program Analysis and Verification');
INSERT INTO ratemycourse.Courses (courseNumber, courseName) VALUES ('CSCI 569', 'Social Media Analytics');
INSERT INTO ratemycourse.Courses (courseNumber, courseName) VALUES ('CSCI 677', 'Advanced Computer Vision');
INSERT INTO ratemycourse.Courses (courseNumber, courseName) VALUES ('CSCI 644', 'Natural Language Dialogue Systems');
INSERT INTO ratemycourse.Courses (courseNumber, courseName) VALUES ('CSCI 656', 'Networked Systems in Cloud Computing');
INSERT INTO ratemycourse.Courses (courseNumber, courseName) VALUES ('CSCI 631', 'Privacy in the World of Big Data');
INSERT INTO ratemycourse.Courses (courseNumber, courseName) VALUES ('CSCI 699', 'Special Topics');
INSERT INTO ratemycourse.Courses (courseNumber, courseName) VALUES ('CSCI 356', 'Introduction to Computer Systems');
INSERT INTO ratemycourse.Courses (courseNumber, courseName) VALUES ('CSCI 102L', 'Fundamentals of Computation');
INSERT INTO ratemycourse.Courses (courseNumber, courseName) VALUES ('CSCI 426', 'Game Prototyping');
INSERT INTO ratemycourse.Courses (courseNumber, courseName) VALUES ('CSCI 563', 'Building Knowledge Graphs');
INSERT INTO ratemycourse.Courses (courseNumber, courseName) VALUES ('CSCI 583', 'Machine Learning Theory');
INSERT INTO ratemycourse.Courses (courseNumber, courseName) VALUES ('CSCI 467', 'Introduction to Machine Learning');
INSERT INTO ratemycourse.Courses (courseNumber, courseName) VALUES ('CSCI 538', 'Augmented, Virtual and Mixed Reality');
INSERT INTO ratemycourse.Courses (courseNumber, courseName) VALUES ('CSCI 659', 'Introduction to Online Optimization');
INSERT INTO ratemycourse.Courses (courseNumber, courseName) VALUES ('CSCI 566', 'Deep Learning and Its Applications');
INSERT INTO ratemycourse.Courses (courseNumber, courseName) VALUES ('CSCI 475', 'Theory of Computation');
INSERT INTO ratemycourse.Courses (courseNumber, courseName) VALUES ('CSCI 477', 'Concepts of Programming Languages');
INSERT INTO ratemycourse.Courses (courseNumber, courseName) VALUES ('CSCI 513', 'Autonomous Cyber-Physical Systems');
INSERT INTO ratemycourse.Courses (courseNumber, courseName) VALUES ('CSCI 655', 'Advanced Topics in Operating Systems');
INSERT INTO ratemycourse.Courses (courseNumber, courseName) VALUES ('CSCI 663', 'Artificial Intelligence for Social Good');
INSERT INTO ratemycourse.Courses (courseNumber, courseName) VALUES ('CSCI 527', 'Applied Machine Learning for Games');
INSERT INTO ratemycourse.Courses (courseNumber, courseName) VALUES ('CSCI 678', 'Theoretical Machine Learning');
INSERT INTO ratemycourse.Courses (courseNumber, courseName) VALUES ('CSCI 532', 'Innovation for Defense Applications');
INSERT INTO ratemycourse.Courses (courseNumber, courseName) VALUES ('CSCI 625', 'Program Synthesis and Computer-Aided Verification');
INSERT INTO ratemycourse.Courses (courseNumber, courseName) VALUES ('CSCI 461', 'Artificial Intelligence for Sustainable Development');
INSERT INTO ratemycourse.Courses (courseNumber, courseName) VALUES ('CSCI 626', 'Text as Data');
INSERT INTO ratemycourse.Courses (courseNumber, courseName) VALUES ('CSCI 667', 'Advanced Topics in Interconnection Network Design and Analysis');
INSERT INTO ratemycourse.Courses (courseNumber, courseName) VALUES ('CSCI 612', 'Optimization for the Information and Data Sciences');
INSERT INTO ratemycourse.Courses (courseNumber, courseName) VALUES ('CSCI 611', 'Mathematics of High-Dimensional Data');
INSERT INTO ratemycourse.Courses (courseNumber, courseName) VALUES ('CSCI 661', 'Advanced Topics in Computer System Architecture');
INSERT INTO ratemycourse.Courses (courseNumber, courseName) VALUES ('CSCI 649', 'Haptic Interfaces and Virtual Environments');
INSERT INTO ratemycourse.Courses (courseNumber, courseName) VALUES ('CSCI 547', 'Robot Dynamics and Control');