DROP DATABASE if exists PUI;

CREATE DATABASE PUI;

USE PUI;

CREATE TABLE users (
    id INT NOT NULL AUTO_INCREMENT,
    email VARCHAR(255) NOT NULL,
    username VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    PRIMARY KEY (id)
);

SELECT * FROM users;
